plugin: amazon.aws.aws_ec2
regions:
  - eu-west-1
filters:
  instance-state-name: running
  "tag:Environment": prod
keyed_groups:
  - key: tags.Role
    prefix: role
hostnames:
  - ip-address
compose:
  ansible_user: ec2-user
  ansible_ssh_private_key_file: "/home/ec2-user/.ssh/id_rsa"  # Change this path
